version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    assignees:
      - "catbuttes"
      - "potzerus"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Check for updates managed by Composer once a week
      interval: "weekly"
    assignees:
      - "catbuttes"
      - "potzerus"
