---
- name: Ensure data persistance location
  file:
    name: "{{ data_persistance_location }}/communitybot/data"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: Authenticate to the github package registry
  community.general.docker_login:
    registry_url: docker.pkg.github.com
    username: "{{docker_registry_user}}"
    password: "{{docker_registry_pass}}"

- name: Start a communitybot container
  docker_container:
    name: communitybot
    image: "docker.pkg.github.com/re-discord-development/communitybot/communitybot:{{communitybot_version}}"
    restart_policy: always
    volumes:
      - "{{ data_persistance_location }}/communitybot/data:/var/lib/communitybot"
    env:
      BOT_TOKEN: "{{ DISCORD_BOT_TOKEN }}"
      BOT_STORAGE: "/var/lib/communitybot"
    published_ports:
      - "9000:9000"
    purge_networks: no
    recreate: yes
    state: started